import figma, { html } from "@figma/code-connect/html";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

/**
 * Check box with label
 */
figma.connect(
  "https://www.figma.com/design/Krub3xbG0vMUdoL8vzEZ7l/%E2%98%84%EF%B8%8F-Meteor-Admin-Foundations-%E2%80%93-6.0.0?node-id=7436-402791&t=l0Um3zKsRc0U0bmx-4",
  {
    props: {
      hint: figma.boolean("Hint"),
      errorMessage: figma.boolean("Error message"),
      error: figma.boolean("Error"),
      checked: figma.boolean("Checked"),
      disabled: figma.boolean("Disabled"),
    },
    example: ({ hint, errorMessage, error, checked, disabled }) =>
      html`<mt-checkbox
        hint=${hint}
        errorMessage=${errorMessage}
        error=${error}
        checked=${checked}
        disabled=${disabled}
      ></mt-checkbox>`,
  },
);
