packages:
  - packages/*
  - examples/*
  - examples/admin-sdk-plugin/src/Resources/app/administration
  - examples/admin-sdk-plugin/tests/acceptance
  - docs/*
  - apps/*

onlyBuiltDependencies:
  - "@swc/core"
  - puppeteer
