import figma, { html } from "@figma/code-connect/html";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/Krub3xbG0vMUdoL8vzEZ7l/%E2%98%84%EF%B8%8F-Meteor-Admin-Foundations-%E2%80%93-6.0.0?node-id=7090-398634&t=0bArnln8EoI5AVWh-4",
  {
    props: {
      placeholder: figma.instance("Placeholder"),
      salesChannelSwitch: figma.boolean("Sales channel switch"),
      title: figma.boolean("Title"),
      contentPadding: figma.boolean("Content padding"),
    },
    example: ({ placeholder, salesChannelSwitch, title, contentPadding }) =>
      html`<mt-card
        placeholder=${placeholder}
        salesChannelSwitch=${salesChannelSwitch}
        title=${title}
        contentPadding=${contentPadding}
      ></mt-card>`,
  },
);
