import figma, { html } from "@figma/code-connect/html";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/Krub3xbG0vMUdoL8vzEZ7l/%E2%98%84%EF%B8%8F-Meteor-Admin-Foundations-%E2%80%93-6.0.0?node-id=6902-400373&t=k3WAKu1UF37jEmyH-4",
  {
    props: {
      label: figma.boolean("Label"),
      flyout: figma.boolean("Flyout"),
      tags: figma.boolean("Tags"),
      hint: figma.boolean("Hint"),
      clearable: figma.boolean("Clearable"),
      size: figma.enum("Size", {
        Default: "default",
        Small: "small",
      }),
      state: figma.enum("State", {
        Default: "default",
        Focus: "focus",
      }),
      inheritedState: figma.enum("Inherited state", {
        None: "none",
        Uninherited: "uninherited",
        Inherited: "inherited",
      }),
      error: figma.boolean("Error"),
      disabled: figma.boolean("Disabled"),
    },
    example: ({
      label,
      flyout,
      tags,
      hint,
      clearable,
      size,
      state,
      inheritedState,
      error,
      disabled,
    }) =>
      html`<mt-select
        label=${label}
        flyout=${flyout}
        tags=${tags}
        hint=${hint}
        clearable=${clearable}
        size=${size}
        state=${state}
        inheritedState=${inheritedState}
        error=${error}
        disabled=${disabled}
      >
      </mt-select>`,
  },
);
