import { test, expect } from "vitest";
import { CSSFile } from "./css-file.js";

test("creates a bare-bones css files", () => {
  // ARRANGE
  const subject = new CSSFile();

  // ACT
  const result = subject.toString();

  // ASSERT
  expect(result).toMatchInlineSnapshot(`
    "/* This file is auto-generated by meteor-icon-kit. */"
  `);
});

test("creates a css file with content", () => {
  // ARRANGE
  const subject = new CSSFile();
  subject.addIcon("my-icon", {
    width: "24px",
    height: "24px",
  });

  // ACT
  const result = subject.toString();

  // ASSERT
  expect(result).toMatchInlineSnapshot(`
    "/* This file is auto-generated by meteor-icon-kit. */

    #meteor-icon-kit__my-icon {
      width: 24px;
      height: 24px;
    }"
  `);
});

test("sorts the id's for the icons in alphabetical order", () => {
  // ARRANGE
  const subject = new CSSFile();
  subject.addIcon("b", {
    width: "24px",
    height: "24px",
  });

  subject.addIcon("a", {
    width: "24px",
    height: "24px",
  });

  // ACT
  const result = subject.toString();

  // ASSSERT
  expect(result).toMatchInlineSnapshot(`
    "/* This file is auto-generated by meteor-icon-kit. */

    #meteor-icon-kit__a {
      width: 24px;
      height: 24px;
    }

    #meteor-icon-kit__b {
      width: 24px;
      height: 24px;
    }"
  `);
});
