name: Bug
description: Issue that results in incorrect or unexpected behavior.
type: Bug
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package(s) are you using?
      multiple: true
      options:
        - "@meteor/admin-sdk"
        - "@meteor/component-library"
        - "@meteor/icon-kit"
        - "@meteor/tokens"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package version
      description: "Which version(s) are you using?"
      placeholder: e.g. 5.2.1

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: In which browser(s) does the issue occur?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      multiple: true
      options:
        - Windows
        - MacOS
        - Other

  - type: input
    id: reproduction-link
    attributes:
      label: Link to minimal reproduction
      description: |
        The easiest way to provide a reproduction is by creating a new project
        in [StackBlitz](https://vite.new/vue). If this is not suitable, you can always provide a GitHub repository. The reproduction should be **minimal** - i.e. it should contain only the
        bare minimum amount of code needed to show the bug.
      placeholder: Reproduction Link

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do in order to make the bug happen?
        Clear and concise reproduction instructions are important for us to be able to
        triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/)
        to format lists and code.
      placeholder: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: Actual behavior
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: Expected behavior
    validations:
      required: true