name: Accessibility Issue
description: Accessibility issue that results in incorrect or unexpected behavior.
type: Bug
labels: ["area/accessibility"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this accessibility issue report!

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package(s) are you using?
      multiple: true
      options:
        - "@meteor/admin-sdk"
        - "@meteor/component-library"
        - "@meteor/icon-kit"
        - "@meteor/tokens"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package version
      description: "Which version(s) are you using?"
      placeholder: e.g. 5.2.1

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: In which browser(s) does the issue occur?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      multiple: true
      options:
        - Windows
        - MacOS
        - Other

  - type: input
    id: technology
    attributes:
      label: Assistive technology
      description: "Did you experience the issue using an assistive technology?"
      placeholder: e.g. MacOS VoiceOver, JAWS

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do in order to reproduce the accessibility issue?
        Clear and concise reproduction instructions are important for us to be able to
        triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/)
        to format lists and code.
      placeholder: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: Actual behavior
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: Expected behavior
    validations:
      required: true

  - type: input
    id: wcag
    attributes:
      label: WCAG 2.1 Violation
      description: "Does this violate a specific WCAG 2.1 checkpoint?"
      placeholder: e.g Success Criteria 1.1 Text Alternatives