import figma, { html } from "@figma/code-connect/html";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  "https://www.figma.com/design/Krub3xbG0vMUdoL8vzEZ7l/%E2%98%84%EF%B8%8F-Meteor-Admin-Foundations-%E2%80%93-6.0.0?node-id=6902-398719&t=0bArnln8EoI5AVWh-4",
  {
    props: {
      hint: figma.boolean("Hint"),
      label: figma.boolean("Label"),
      copyable: figma.boolean("Copyable"),
      size: figma.enum("Size", {
        Default: "default",
        Small: "small",
      }),
      state: figma.enum("State", {
        Default: "default",
        Focus: "focus",
      }),
      error: figma.boolean("Error"),
      disabled: figma.boolean("Disabled"),
    },
    example: ({ hint, label, copyable, size, state, error, disabled }) =>
      html`<mt-number-field
        hint=${hint}
        label=${label}
        copyable=${copyable}
        size=${size}
        state=${state}
        error=${error}
        disabled=${disabled}
      ></mt-number-field>`,
  },
);
